spring.application.name=order-service
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_order?options=-c%20timezone%3DUTC
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ==============================
# Resilience4j TimeLimiter
# ==============================

resilience4j.timelimiter.instances.inventoryService.timeoutDuration=3s
resilience4j.timelimiter.instances.inventoryService.cancelRunningFuture=true

# ==============================
# Resilience4j Circuit Breaker
# ==============================

resilience4j.circuitbreaker.instances.inventoryService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.inventoryService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.inventoryService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.inventoryService.automaticTransitionFromOpenToHalfOpenEnabled=true

# ==============================
# OpenFeign Circuit Breaker
# ==============================

spring.cloud.openfeign.circuitbreaker.enabled=true
